spring:
  application:
    name: ledgerflow
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledgerflow}
    username: ${DB_USERNAME:ledgerflow_app}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledgerflow}
    user: ${DB_MIGRATION_USERNAME:ledgerflow_migrator}
    password: ${DB_MIGRATION_PASSWORD}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      accept-float-as-int: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: ${ledgerflow.events.enabled}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 3000
        request.timeout.ms: 2000
        max.block.ms: 2000
        linger.ms: 5
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 20
    listener:
      ack-mode: record
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
logging:
  structured:
    format:
      console: ecs
ledgerflow:
  events:
    enabled: ${EVENTS_ENABLED:false}
    topic: ledgerflow.events.v1
  auth:
    issuer: ${JWT_ISSUER:urn:ledgerflow:local}
    private-key: ${JWT_PRIVATE_KEY:file:../.local-secrets/jwt-private.pem}
    public-key: ${JWT_PUBLIC_KEY:file:../.local-secrets/jwt-public.pem}
