import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('register, fund, transfer, inspect ledger and reconcile through real APIs', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const email = `e2e-${randomUUID()}@example.test`; const password = `E2e-password-${randomUUID()}`;
  await page.goto('/');
  await page.getByRole('button', { name: 'New to LedgerFlow? Create an account' }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByLabel('Merchant name', { exact: true }).fill('E2E Commerce');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your money movements, at a glance.' })).toBeVisible();
  await page.getByRole('link', { name: 'Wallets', exact: true }).click();
  await page.getByLabel('Wallet name', { exact: true }).fill('Customer wallet');
  await page.getByRole('button', { name: 'Create wallet', exact: true }).click();
  await expect(page).toHaveURL(/\/wallets\/[0-9a-f-]+$/);
  const source = page.url().split('/').pop()!;
  await page.getByLabel('Amount (paise)', { exact: true }).fill('10000');
  await page.getByRole('button', { name: 'Add simulated funds', exact: true }).click();
  await expect(page.getByRole('heading', { name: '₹100.00', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Wallets', exact: true }).click();
  await page.getByLabel('Wallet name', { exact: true }).fill('Settlement wallet');
  await page.getByLabel('Type', { exact: true }).selectOption('SETTLEMENT');
  await page.getByRole('button', { name: 'Create wallet', exact: true }).click();
  await expect(page).toHaveURL(/\/wallets\/[0-9a-f-]+$/);
  const destination = page.url().split('/').pop()!;
  await page.getByRole('link', { name: 'Transfers', exact: true }).click();
  await page.getByLabel('Source wallet UUID', { exact: true }).fill(source);
  await page.getByLabel('Destination wallet UUID', { exact: true }).fill(destination);
  await page.getByLabel('Amount (paise)', { exact: true }).fill('2500');
  await page.getByRole('button', { name: 'Transfer funds', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Transfer detail', exact: true })).toBeVisible();
  await page.locator('a.id-link').click();
  await expect(page.getByRole('heading', { name: 'Journal entry', exact: true })).toBeVisible();
  await expect(page.getByText('BALANCED', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/ledger.png', fullPage: true });
  await page.getByRole('link', { name: 'Payments', exact: true }).click();
  await page.getByLabel('Customer wallet UUID', { exact: true }).fill(source);
  await page.getByLabel('Amount (paise)', { exact: true }).fill('1000');
  await page.getByLabel('Order reference', { exact: true }).fill('E2E-ORDER-1');
  await page.getByRole('button', { name: 'Create payment', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Payment detail' })).toBeVisible();
  await page.getByRole('button', { name: 'Confirm payment', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm confirm payment', exact: true }).click();
  await expect(page.locator('.facts .status')).toHaveText('SUCCEEDED');
  await page.getByLabel('Amount (paise)', { exact: true }).fill('250');
  await page.getByRole('button', { name: 'Issue refund', exact: true }).click();
  await expect(page.locator('.facts .status')).toHaveText('PARTIALLY REFUNDED');
  await page.getByLabel('Amount (paise)', { exact: true }).fill('');
  await page.getByRole('button', { name: 'Issue refund', exact: true }).click();
  await expect(page.locator('.facts .status')).toHaveText('REFUNDED');
  await page.getByRole('link', { name: 'API keys', exact: true }).click();
  await page.getByLabel('Key name', { exact: true }).fill('E2E integration');
  await page.getByRole('button', { name: 'Create API key', exact: true }).click();
  await expect(page.getByLabel('New secret')).toHaveValue(/^lf_test_/);
  await page.getByRole('button', { name: 'I saved it — dismiss' }).click();
  await expect(page.getByLabel('New secret')).toHaveCount(0);
  await page.getByRole('button', { name: 'Revoke', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm revoke', exact: true }).click();
  await expect(page.getByText('REVOKED', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Operations', exact: true }).click();
  await page.getByRole('button', { name: 'Start reconciliation', exact: true }).click();
  await expect(page.getByText('PASSED', { exact: true })).toBeVisible({ timeout: 20_000 });
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await page.screenshot({ path: 'test-results/overview.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'Your money movements, at a glance.' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.getByLabel('Email', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your money movements, at a glance.' })).toBeVisible();
  expect(errors).toEqual([]);
});
